<?php

use App\Http\Controllers\ActivityController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\AttendanceReportController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\HolidayController;
use App\Http\Controllers\ImportController;
use App\Http\Controllers\InverterController;
use App\Http\Controllers\ISolarCloudController;
use App\Http\Controllers\LeaveController;
use App\Http\Controllers\PlantPhotoController;
use App\Http\Controllers\PlantReelController;
use App\Http\Controllers\ReadingController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SalaryController;
use App\Http\Controllers\SharedExpenseController;
use App\Http\Controllers\SolarCurtailmentController;
use App\Http\Controllers\EmployeeLocationController;
use App\Http\Controllers\PushNotificationController;
use App\Http\Controllers\StockBorrowingController;
use App\Http\Controllers\StockItemController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
})->name('login');

Route::prefix('api')->group(function () {
    Route::get('isolarcloud/callback', [ISolarCloudController::class, 'callback']);
    Route::post('login', [AuthController::class, 'login']);
    Route::middleware('auth')->group(function () {
        Route::get('me', [AuthController::class, 'me']);
        Route::post('logout', [AuthController::class, 'logout']);
        Route::get('dashboard/live-solar', [ISolarCloudController::class, 'liveDashboard']);
        Route::post('dashboard/plant-location', [ISolarCloudController::class, 'updatePlantLocation']);
        Route::post('plant-location', [ISolarCloudController::class, 'updatePlantLocation']);
        Route::get('isolarcloud/status', [ISolarCloudController::class, 'status']);
        Route::get('isolarcloud/auth-url', [ISolarCloudController::class, 'authUrl']);
        Route::post('isolarcloud/manual-token', [ISolarCloudController::class, 'manualToken']);
        Route::get('isolarcloud/live', [ISolarCloudController::class, 'liveData']);
        Route::post('isolarcloud/sync', [ISolarCloudController::class, 'sync']);
        Route::get('curtailments', [SolarCurtailmentController::class, 'index']);
        Route::post('curtailments', [SolarCurtailmentController::class, 'store']);
        Route::post('curtailments/restore-all', [SolarCurtailmentController::class, 'restoreAll']);
        Route::delete('curtailments/{curtailment}', [SolarCurtailmentController::class, 'destroy']);
        Route::post('isolarcloud/sync-daily', [ISolarCloudController::class, 'sync']);
        Route::get('plant-photos/tasks', [PlantPhotoController::class, 'tasks']);
        Route::post('plant-photos/tasks', [PlantPhotoController::class, 'saveTask']);
        Route::delete('plant-photos/tasks/{task}', [PlantPhotoController::class, 'deleteTask']);
        Route::post('plant-photos/upload', [PlantPhotoController::class, 'upload']);
        Route::get('plant-photos/gallery', [PlantPhotoController::class, 'gallery']);
        Route::delete('plant-photos/{photo}', [PlantPhotoController::class, 'deletePhoto']);
        Route::get('plant-photos/{photo}/image', [PlantPhotoController::class, 'image'])->name('plant-photos.image');
        Route::get('plant-reels', [PlantReelController::class, 'index']);
        Route::post('plant-reels', [PlantReelController::class, 'store']);
        Route::delete('plant-reels/{reel}', [PlantReelController::class, 'destroy']);
        Route::get('plant-reels/{reel}/video', [PlantReelController::class, 'video'])->name('plant-reels.video');
        Route::get('plant-reels/{reel}/thumbnail', [PlantReelController::class, 'thumbnail'])->name('plant-reels.thumbnail');
        Route::post('plant-reels/{reel}/like', [PlantReelController::class, 'like']);
        Route::post('plant-reels/{reel}/view', [PlantReelController::class, 'view']);
        Route::get('companies', [CompanyController::class, 'index']);
        Route::post('companies', [CompanyController::class, 'store']);
        Route::get('companies/{company}/logo', [CompanyController::class, 'logo'])->name('companies.logo');
        Route::get('companies/{company}/owner-photo', [CompanyController::class, 'ownerPhoto'])->name('companies.owner-photo');
        Route::post('inverters', [InverterController::class, 'store']);
        Route::get('users', [UserController::class, 'index']);
        Route::post('users', [UserController::class, 'store']);
        Route::get('dashboard', [DashboardController::class, 'show']);
        Route::get('readings', [ReadingController::class, 'index']);
        Route::post('readings', [ReadingController::class, 'store']);
        Route::get('report', [ReportController::class, 'show']);
        Route::get('report/export/excel', [ReportController::class, 'excel']);
        Route::get('report/export/daily-ss-excel', [ReportController::class, 'dailySsExcel']);
        Route::get('report/export/company-excel', [ReportController::class, 'companyExcel']);
        Route::get('report/export/pdf', [ReportController::class, 'pdf']);
        Route::post('import/excel', [ImportController::class, 'store']);
        Route::get('activity', [ActivityController::class, 'index']);
        Route::get('employees', [EmployeeController::class, 'index']);
        Route::post('employees', [EmployeeController::class, 'store']);
        Route::get('employees/{employee}/photo', [EmployeeController::class, 'photo'])->name('employees.photo');
        Route::get('attendance/today', [AttendanceController::class, 'today']);
        Route::get('attendance/mine', [AttendanceController::class, 'mine']);
        Route::post('attendance/clock-in', [AttendanceController::class, 'clockIn']);
        Route::post('attendance/clock-out', [AttendanceController::class, 'clockOut']);
        Route::post('attendance/break-in', [AttendanceController::class, 'startBreak']);
        Route::post('attendance/break-out', [AttendanceController::class, 'endBreak']);
        Route::post('attendance/manual', [AttendanceController::class, 'manual']);
        Route::get('attendance/breaks/{attendanceBreak}/selfie', [AttendanceController::class, 'breakSelfie'])->name('attendance.break-selfie');
        Route::get('attendance', [AttendanceController::class, 'index']);
        Route::post('attendance/{attendanceRecord}/correct', [AttendanceController::class, 'correct']);
        Route::get('attendance/{attendanceRecord}/selfie', [AttendanceController::class, 'selfie'])->name('attendance.selfie');
        Route::post('employee-locations/ping', [EmployeeLocationController::class, 'ping']);
        Route::get('employee-locations/live', [EmployeeLocationController::class, 'live']);
        Route::get('push-notifications/public-key', [PushNotificationController::class, 'publicKey']);
        Route::post('push-notifications/subscribe', [PushNotificationController::class, 'subscribe']);
        Route::post('push-notifications/send-test', [PushNotificationController::class, 'sendTest']);
        Route::post('push-notifications/broadcast', [PushNotificationController::class, 'broadcast']);
        Route::get('holidays', [HolidayController::class, 'index']);
        Route::post('holidays', [HolidayController::class, 'store']);
        Route::get('leave-types', [LeaveController::class, 'types']);
        Route::get('leaves/mine', [LeaveController::class, 'mine']);
        Route::post('leaves', [LeaveController::class, 'store']);
        Route::get('leaves', [LeaveController::class, 'index']);
        Route::post('leaves/{leaveRequest}/review', [LeaveController::class, 'review']);
        Route::get('attendance-report', [AttendanceReportController::class, 'show']);
        Route::get('attendance-report/export/excel', [AttendanceReportController::class, 'excel']);
        Route::get('attendance-report/export/pdf', [AttendanceReportController::class, 'pdf']);
        Route::get('salaries', [SalaryController::class, 'index']);
        Route::get('salaries/export/excel', [SalaryController::class, 'excel']);
        Route::get('my-salary', [SalaryController::class, 'mine']);
        Route::get('employees/{employee}/salary-rates', [SalaryController::class, 'rates']);
        Route::post('employees/{employee}/salary-rates', [SalaryController::class, 'storeRate']);
        Route::post('salary-adjustments', [SalaryController::class, 'storeAdjustment']);
        Route::post('salary-adjustments/{adjustment}/cancel', [SalaryController::class, 'cancelAdjustment']);
        Route::get('stock/items', [StockItemController::class, 'index']);
        Route::post('stock/items', [StockItemController::class, 'store']);
        Route::post('stock/items/{stockItem}/add', [StockItemController::class, 'add']);
        Route::get('stock/items/{stockItem}/image', [StockItemController::class, 'image'])->name('stock.items.image');
        Route::get('stock/borrowings', [StockBorrowingController::class, 'index']);
        Route::post('stock/borrowings', [StockBorrowingController::class, 'store']);
        Route::post('stock/borrowings/{stockBorrowing}/returns', [StockBorrowingController::class, 'receive']);
        Route::get('stock/people', [StockBorrowingController::class, 'people']);
        Route::get('expenses', [SharedExpenseController::class, 'index']);
        Route::get('expenses/export/excel', [SharedExpenseController::class, 'excel']);
        Route::post('expense-percentages', [SharedExpenseController::class, 'percentages']);
        Route::post('expenses', [SharedExpenseController::class, 'store']);
        Route::post('expenses/{expense}', [SharedExpenseController::class, 'update']);
        Route::post('expenses/{expense}/cancel', [SharedExpenseController::class, 'cancel']);
        Route::post('expenses/{expense}/reverse', [SharedExpenseController::class, 'reverse']);
        Route::post('expense-settlements', [SharedExpenseController::class, 'settle']);
        Route::get('expenses/{expense}/receipt', [SharedExpenseController::class, 'receipt'])->name('expenses.receipt');
    });
});
