<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        @page { margin: 24px; }
        body { font-family: DejaVu Sans, sans-serif; color: #17352b; font-size: 10px; }
        h1 { margin: 0 0 5px; font-size: 20px; }
        .meta { color: #667b70; margin-bottom: 18px; }
        .reference { background: #eef5ef; border-left: 4px solid #2f7759; padding: 8px 10px; margin: -8px 0 14px; }
        .warning { background: #fff7df; border-left: 4px solid #d39a21; color: #74540e; padding: 8px 10px; margin: -5px 0 14px; }
        .totals { width: 100%; margin-bottom: 18px; border-collapse: separate; border-spacing: 7px 0; }
        .totals td { background: #edf5ef; padding: 10px; border-radius: 5px; }
        .totals span { display: block; color: #63796d; font-size: 8px; text-transform: uppercase; margin-bottom: 5px; }
        .totals b { font-size: 14px; }
        table.report { width: 100%; border-collapse: collapse; }
        .report th { background: #245f49; color: white; padding: 8px 6px; text-align: right; }
        .report th:first-child, .report td:first-child { text-align: left; }
        .report td { padding: 7px 6px; border-bottom: 1px solid #dce7df; text-align: right; }
        .report tr:nth-child(even) td { background: #f6f9f7; }
        h2 { margin: 18px 0 7px; font-size: 13px; }
        .footer { position: fixed; bottom: -12px; left: 0; right: 0; text-align: center; color: #89988f; font-size: 8px; }
    </style>
</head>
<body>
    <h1>SolarFlow {{ ucfirst($report['period']) }} Report</h1>
    <div class="meta">{{ $report['from'] }} to {{ $report['to'] }} · {{ $report['is_combined'] ? 'All companies combined' : 'Selected company' }}</div>
    @if($report['is_combined'] && $report['ss_reference'])
        <div class="reference"><b>Daily SS reference company:</b> {{ $report['ss_reference']['company'] }}</div>
        @if(count($report['ss_reference']['missing_dates']))
            <div class="warning"><b>Missing reference dates:</b> {{ implode(', ', $report['ss_reference']['missing_dates']) }}. 66kV Sub Import contributes 0.00 for these dates.</div>
        @endif
    @endif
    <table class="totals"><tr>
        <td><span>All Inverter Total</span><b>{{ number_format($report['grand_total']['generation'], 2) }} kWh</b></td>
        <td><span>Plant Import</span><b>{{ number_format($report['grand_total']['plant_import'], 2) }}</b></td>
        <td><span>Plant Export</span><b>{{ number_format($report['grand_total']['plant_export'], 2) }}</b></td>
        <td><span>66kV Import</span><b>{{ number_format($report['grand_total']['sub_import'], 2) }}</b></td>
        <td><span>66kV Export</span><b>{{ number_format($report['grand_total']['sub_export'], 2) }}</b></td>
    </tr></table>
    <table class="report">
        <thead><tr><th>Period</th><th>All Inverter Total (kWh)</th><th>Plant Import</th><th>Plant Export</th><th>66kV Import</th><th>66kV Export</th></tr></thead>
        <tbody>
        @forelse($report['rows'] as $row)
            <tr><td>{{ $row['period'] }}</td><td>{{ number_format($row['generation'], 2) }}</td><td>{{ number_format($row['plant_import'], 2) }}</td><td>{{ number_format($row['plant_export'], 2) }}</td><td>{{ number_format($row['sub_import'], 2) }}</td><td>{{ number_format($row['sub_export'], 2) }}</td></tr>
        @empty
            <tr><td colspan="6">No readings found for this period.</td></tr>
        @endforelse
        </tbody>
    </table>
    @if($report['is_combined'] && count($report['company_totals']))
        <h2>Company-wise totals</h2>
        <table class="report">
            <thead><tr><th>Company</th><th>All Inverter Total (kWh)</th><th>Plant Import</th><th>Plant Export</th><th>66kV Import</th><th>66kV Export</th></tr></thead>
            <tbody>@foreach($report['company_totals'] as $total)<tr><td>{{ $total['company'] }}</td><td>{{ number_format($total['generation'], 2) }}</td><td>{{ number_format($total['plant_import'], 2) }}</td><td>{{ number_format($total['plant_export'], 2) }}</td><td>{{ number_format($total['sub_import'], 2) }}</td><td>{{ number_format($total['sub_export'], 2) }}</td></tr>@endforeach</tbody>
        </table>
    @endif
    @if(count($report['inverter_totals']))
        <h2>Inverter-wise generation totals</h2>
        <table class="report">
            <thead><tr><th>Company</th><th>Inverter</th><th>Generation (kWh)</th></tr></thead>
            <tbody>@foreach($report['inverter_totals'] as $total)<tr><td>{{ $total['company'] }}</td><td>{{ $total['inverter'] }}</td><td>{{ number_format($total['generation'], 2) }}</td></tr>@endforeach</tbody>
        </table>
    @endif
    <div class="footer">Generated by SolarFlow</div>
</body>
</html>
